# Generated by Django 4.0.3 on 2022-03-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_comment_author_alter_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
    ]
