# Generated by Django 3.2.12 on 2022-03-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="creator",
            field=models.CharField(default="me", max_length=50),
        ),
    ]
